// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXGQQhbD9wucgPmiO0PrO4e3gsoCgTHps',
    appId: '1:821865982842:web:209ecdf983c874842704c3',
    messagingSenderId: '821865982842',
    projectId: 'water-reminder-app-3a311',
    authDomain: 'water-reminder-app-3a311.firebaseapp.com',
    storageBucket: 'water-reminder-app-3a311.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl8qKL-KN1MnZR1lIMmvTHmZiAkk_GpZ4',
    appId: '1:821865982842:android:852c960df8fdc8cd2704c3',
    messagingSenderId: '821865982842',
    projectId: 'water-reminder-app-3a311',
    storageBucket: 'water-reminder-app-3a311.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoYH-f2ZN2i65LNUdYfu-KIA2MfwRJB8I',
    appId: '1:821865982842:ios:fae57fafd6d8858c2704c3',
    messagingSenderId: '821865982842',
    projectId: 'water-reminder-app-3a311',
    storageBucket: 'water-reminder-app-3a311.firebasestorage.app',
    iosBundleId: 'com.example.coffeeTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoYH-f2ZN2i65LNUdYfu-KIA2MfwRJB8I',
    appId: '1:821865982842:ios:fae57fafd6d8858c2704c3',
    messagingSenderId: '821865982842',
    projectId: 'water-reminder-app-3a311',
    storageBucket: 'water-reminder-app-3a311.firebasestorage.app',
    iosBundleId: 'com.example.coffeeTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXGQQhbD9wucgPmiO0PrO4e3gsoCgTHps',
    appId: '1:821865982842:web:e0dae129572c878b2704c3',
    messagingSenderId: '821865982842',
    projectId: 'water-reminder-app-3a311',
    authDomain: 'water-reminder-app-3a311.firebaseapp.com',
    storageBucket: 'water-reminder-app-3a311.firebasestorage.app',
  );
}
